name: Kuba Łojewski
description: International affairs expert. Renegade economist. Brewer, corporate PM, technology wizard, connoisseur
meta_description: "International affairs expert. Renegade economist. Brewer, corporate PM, technology wizard, connoisseur"
url: http://trytotrust.me

author: Kuba Łojewski
markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'http://lojewski.github.io'
permalink: /:title
